# Generated by Django 5.2.7 on 2025-11-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_car_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default='2025-11-02'),
            preserve_default=False,
        ),
    ]
