# Generated by Django 5.2.7 on 2025-11-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_reservation_created_at_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-11-02 15:25'),
            preserve_default=False,
        ),
    ]
