# Generated by Django 5.2.7 on 2025-11-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_reservation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
